### PR TITLE
Feature/settings screen

### PR DESCRIPTION
**Pull request by tonelli-m**
# Description

Adds a settings screen to tweak persistent app settings

## Changes

- Added a crossplaform user settings service to manage persistently stored settings using the [Settings Multiplatform](https://github.com/russhwolf/multiplatform-settings) library
  - Android settings are stored using `SharedPreferences`
  - iOS settings are stored using `NSUserDefaults`
  - Web settings are stored using `Storage`
  - Any serializable type can be stored, associated to a unique key and a default value
  - Settings values can be retrieved as a one time thing or as a `Flow<T>` to listen to value changes
- Added a settings screen with a list of all settings
- Bumped dependencies to latest versions
 
## Linked issues

#44 

## Remaining TODOs

UI could still be improved (especially on small phones and on web) but I'm saving this for later when we'll do a general UI/UX improvement work over the whole app to ensure style consistency.

## Checklist

- [x] Code compiles correctly on all platforms
- [x] All pre-existing tests are passing
- [x] If needed, new tests have been added
- [x] Extended the README / documentation if necessary
- [x] Added code has been documented

### CODE REVIEW

**Comment by nicolas-f** [comment]
thanks for pr
Build is failing
https://github.com/Universite-Gustave-Eiffel/NoiseCaptureClient/actions/runs/11895421666

**Comment by tonelli-m** [comment]
@nicolas-f my bad, build is now fixed 👍 

I've also set the github actions workflow to also run for PRs targetting the `dev` branch

**Comment by nicolas-f** [comment]
maybe we should remove dev branch and find a way to build only the last release for the github page ?

**Comment by nicolas-f** [comment]
maybe we should remove dev branch and find a way to build only the last release for the github page ?

**Pull request merged**
